-- Create tags table
CREATE TABLE tags
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_tags_name ON tags (name);

-- MySQL's ON UPDATE CURRENT_TIMESTAMP has no Postgres equivalent, so updated_at
-- needs a trigger to keep behaving the same way. Without it the column silently
-- stops advancing on UPDATE -- nothing errors, the value just goes stale.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tags_set_updated_at BEFORE UPDATE ON tags
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Create anime_tags junction table for many-to-many relationship
-- Note: Foreign keys were not used due to Vitess/PlanetScale compatibility.
-- Postgres has no such limitation, but they are left off here so this migration
-- reproduces the schema it did on MySQL. Adding them is a later decision, not a
-- side effect of changing engine.
CREATE TABLE anime_tags
(
    anime_id   VARCHAR(36) NOT NULL,
    tag_id     BIGINT NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (anime_id, tag_id)
);
CREATE INDEX idx_anime_tags_anime_id ON anime_tags (anime_id);
CREATE INDEX idx_anime_tags_tag_id ON anime_tags (tag_id);

-- Migrate existing genres data to tags.
--
-- JSON_TABLE becomes jsonb_array_elements_text, which is the direct equivalent
-- and needs no COLUMNS clause. Two MySQL-isms disappear entirely:
--
--   JSON_VALID  -> pg_input_is_valid(text, 'jsonb'), available since PG 16.
--                  Needed for the same reason: genres is a text column and not
--                  every row holds valid JSON.
--   COLLATE     -> gone. The original forced a common collation on both sides
--                  of the join because two MySQL defaults met there and raised
--                  "Illegal mix of collations". Postgres has one collation for
--                  the database, so the comparison is simply valid.
INSERT INTO tags (name)
SELECT DISTINCT TRIM(j.genre) AS tag_name
FROM anime a
CROSS JOIN LATERAL jsonb_array_elements_text(a.genres::jsonb) AS j(genre)
WHERE a.genres IS NOT NULL
  AND pg_input_is_valid(a.genres, 'jsonb')
  AND TRIM(j.genre) <> ''
ON CONFLICT (name) DO NOTHING;

-- Populate anime_tags junction table from existing genres data.
-- ON DUPLICATE KEY UPDATE name = name was MySQL's way of saying "ignore
-- conflicts"; ON CONFLICT DO NOTHING says it directly.
INSERT INTO anime_tags (anime_id, tag_id)
SELECT DISTINCT a.id, t.id
FROM anime a
CROSS JOIN LATERAL jsonb_array_elements_text(a.genres::jsonb) AS j(genre)
INNER JOIN tags t ON t.name = TRIM(j.genre)
WHERE a.genres IS NOT NULL
  AND pg_input_is_valid(a.genres, 'jsonb')
  AND TRIM(j.genre) <> ''
ON CONFLICT (anime_id, tag_id) DO NOTHING;
