-- Drops idx_anime_title_jp on anime (title_jp).
--
-- Same leading-wildcard search as 000052. A btree cannot serve LIKE '%term%'.
--
-- Reclaims 2600 kB.
--
-- CONCURRENTLY, and alone in this file. golang-migrate hands the whole file to
-- one Exec, and Postgres runs a multi-statement simple query as an implicit
-- transaction -- where this is rejected with "DROP INDEX CONCURRENTLY cannot
-- run inside a transaction block". One statement per file keeps it out of one.
DROP INDEX CONCURRENTLY IF EXISTS idx_anime_title_jp;
