-- Drops idx_anime_ranking on anime (ranking).
--
-- A leading prefix of idx_anime_ranking_id (ranking, id).
--
-- Reclaims 1192 kB.
--
-- CONCURRENTLY, and alone in this file. golang-migrate hands the whole file to
-- one Exec, and Postgres runs a multi-statement simple query as an implicit
-- transaction -- where this is rejected outright with "DROP INDEX CONCURRENTLY
-- cannot run inside a transaction block". One statement per file is what keeps
-- it out of a transaction.
--
-- It matters here: a plain DROP INDEX takes ACCESS EXCLUSIVE, and
-- anime_character_staff_link is taking tens of thousands of sequential scans,
-- so the drop would queue behind one and block every reader after it.
DROP INDEX CONCURRENTLY IF EXISTS idx_anime_ranking;
