-- Drops idx_anime_created_at on anime (created_at).
--
-- Covered by idx_anime_created_at_id (created_at DESC, id). The differing sort
-- direction does not matter: btrees scan backwards, so the wider index serves
-- ascending order and range predicates on created_at alike.
--
-- Reclaims 528 kB.
--
-- CONCURRENTLY, and alone in this file. golang-migrate hands the whole file to
-- one Exec, and Postgres runs a multi-statement simple query as an implicit
-- transaction -- where this is rejected outright with "DROP INDEX CONCURRENTLY
-- cannot run inside a transaction block". One statement per file is what keeps
-- it out of a transaction.
--
-- It matters here: a plain DROP INDEX takes ACCESS EXCLUSIVE, and
-- anime_character_staff_link is taking tens of thousands of sequential scans,
-- so the drop would queue behind one and block every reader after it.
DROP INDEX CONCURRENTLY IF EXISTS idx_anime_created_at;
