version: "2.2"
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=weeb
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=weeb
    volumes:
      - 'weeb-api_db:/var/lib/mysql'
    networks:
      - weeb-api-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:5.0.5
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - './redis.conf:/etc/redis/redis.conf'
      - redis_data:/data
    networks:
      - weeb-api-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  anime-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "local"
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=weeb
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=weeb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_ENABLED=true
      - PORT=3000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - weeb-api-network
    restart: unless-stopped
    volumes:
      - './config:/app/config:ro'

networks:
  weeb-api-network:

volumes:
  weeb-api_db:
  redis_data: