package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	"errors"
	"fmt"

	"github.com/weeb-vip/anime-api/graph/generated"
	"github.com/weeb-vip/anime-api/graph/model"
	"github.com/weeb-vip/anime-api/internal/resolvers"
	"gorm.io/gorm"
)

// FindAnimeByID is the resolver for the findAnimeByID field.
//
// Another subgraph answered with an Anime it does not own -- the feed in
// notifications-service returns Anime{id} -- and the router comes here to
// fill in the rest. Batched: the router sends one _entities request per page
// of activities, and the per-request dataloader turns those into one query.
// An unknown id is a null, not an error, so one stale reference cannot take
// down a whole page of someone else's data.
func (r *entityResolver) FindAnimeByID(ctx context.Context, id string) (*model.Anime, error) {
	found, err := resolvers.AnimeByIDBatched(ctx, r.AnimeService, id)
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	return found, err
}

// FindEpisodeByAnimeID is the resolver for the findEpisodeByAnimeID field.
func (r *entityResolver) FindEpisodeByAnimeID(ctx context.Context, animeID *string) (*model.Episode, error) {
	panic(fmt.Errorf("not implemented: FindEpisodeByAnimeID - findEpisodeByAnimeID"))
}

// FindUserAnimeByAnimeID is the resolver for the findUserAnimeByAnimeID field.
func (r *entityResolver) FindUserAnimeByAnimeID(ctx context.Context, animeID string) (*model.UserAnime, error) {
	// this shouldn't do any checks since this is for federation
	return &model.UserAnime{
		AnimeID: animeID,
	}, nil
}

// FindUserWorkByWorkID is the resolver for the findUserWorkByWorkID field.
//
// The reading counterpart of FindUserAnimeByAnimeID. It builds a stub carrying
// only the key the router handed over; the work field resolver does the actual
// lookup. No checks here -- this is federation plumbing, not a request the
// viewer made.
func (r *entityResolver) FindUserWorkByWorkID(ctx context.Context, workID string) (*model.UserWork, error) {
	return &model.UserWork{
		WorkID: workID,
	}, nil
}

// FindWorkByID is the resolver for the findWorkByID field.
//
// Same contract as FindAnimeByID: a Work reference arrives here from any
// subgraph that hangs a field off a work it does not own.
func (r *entityResolver) FindWorkByID(ctx context.Context, id string) (*model.Work, error) {
	return resolvers.WorkByID(ctx, r.WorkService, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
