"""Generate the Postgres baseline from the schema the MySQL migrations actually
produce, rather than from a reading of what they were meant to produce.

Input is information_schema, captured after applying all 37 up-migrations to a
throwaway MySQL. That matters: hand-translating the migrations would reproduce
their bugs (see idx_relations_* below) and miss the drift between intent and
result.
"""
import re, sys
from collections import OrderedDict

OUT = sys.argv[1] if len(sys.argv) > 1 else "."

cols = OrderedDict()
for line in open(f"{OUT}/cols.txt"):
    line = line.rstrip("\n")
    if not line:
        continue
    t, c, typ, nullable, default, extra = line.split("|", 5)
    cols.setdefault(t, []).append(
        dict(name=c, type=typ, nullable=nullable, default=default, extra=extra)
    )

idx = {}
pk = {}
for line in open(f"{OUT}/idx.txt"):
    line = line.strip()
    if not line:
        continue
    m = re.match(r"^(\S+)\s+(\S+)\s+\[([^\]]*)\](\s+UNIQUE)?$", line)
    if not m:
        continue
    tbl, name, colstr, uniq = m.groups()
    if name == "PRIMARY":
        pk[tbl] = [c.strip() for c in colstr.split(",")]
    else:
        idx.setdefault(tbl, []).append(
            dict(name=name, cols=[c.strip() for c in colstr.split(",")], unique=bool(uniq))
        )

# ------------------------------------------------- index dedupe and name fixing
#
# Two things MySQL tolerates that Postgres does not, both found by applying this
# to a real Postgres rather than by reading the migrations:
#
#   1. Index names are per-table in MySQL and schema-global in Postgres, and
#      Postgres folds unquoted identifiers to lowercase. anime_character has
#      "idx_anime_id" and anime_seasons has "IDX_anime_id" -- distinct in MySQL,
#      the same name in Postgres.
#
#   2. Five (table, columns) pairs carry two indexes each. Duplicates cost write
#      throughput and storage for nothing, so only one survives. Where one of the
#      pair is UNIQUE it is the one kept -- it enforces a constraint the other
#      does not, and it serves every lookup the redundant one would have.
notes = []
for tbl, lst in idx.items():
    by_cols = {}
    for i in lst:
        by_cols.setdefault(tuple(i["cols"]), []).append(i)
    kept = []
    for colkey, group in by_cols.items():
        if len(group) == 1:
            kept.append(group[0])
            continue
        uniq = [g for g in group if g["unique"]]
        # Prefer a UNIQUE index; otherwise the most descriptive (longest) name.
        winner = uniq[0] if uniq else max(group, key=lambda g: len(g["name"]))
        dropped = [g["name"] for g in group if g is not winner]
        notes.append(
            f"--   {tbl} ({', '.join(colkey)}): kept {winner['name']}"
            f"{' UNIQUE' if winner['unique'] else ''}, dropped {', '.join(dropped)}"
        )
        kept.append(winner)
    idx[tbl] = kept

# Now resolve case-insensitive collisions across the whole schema.
seen = {}
for tbl, lst in idx.items():
    for i in lst:
        key = i["name"].lower()
        if key in seen:
            new = f"{tbl}_{i['name']}".lower()
            notes.append(f"--   renamed {i['name']} on {tbl} to {new} (collides with {seen[key]})")
            i["name"] = new
        else:
            seen[key] = f"{i['name']} on {tbl}"
            i["name"] = i["name"].lower()


# ---------------------------------------------------------------- type mapping
def pgtype(col):
    t = col["type"]
    if col["extra"] == "auto_increment":
        return "bigint GENERATED BY DEFAULT AS IDENTITY"
    if t.startswith("enum("):
        return "text"          # constrained by CHECK below; see note in header
    if t == "timestamp":
        return "timestamptz"
    if t == "date":
        return "date"
    if t == "int":
        return "integer"
    if t == "bigint":
        return "bigint"
    if t == "json":
        return "jsonb"
    if t == "text":
        return "text"
    m = re.match(r"decimal\((\d+),(\d+)\)", t)
    if m:
        return f"numeric({m.group(1)},{m.group(2)})"
    m = re.match(r"varchar\((\d+)\)", t)
    if m:
        return f"varchar({m.group(1)})"
    m = re.match(r"char\((\d+)\)", t)
    if m:
        return f"char({m.group(1)})"
    raise SystemExit(f"unmapped type: {t}")


def enum_values(t):
    return re.findall(r"'([^']*)'", t[len("enum("):-1])


# anime_staff.url_slug: the 70-branch REPLACE chain becomes one unaccent() call.
URL_SLUG_EXPR = (
    "nullif(trim(both '-' from "
    "regexp_replace(lower(immutable_unaccent(coalesce(given_name,'') || ' ' || "
    "coalesce(family_name,''))), '[^a-z0-9]+', '-', 'g')), '')"
)

lines = []
w = lines.append

w("-- Postgres baseline for anime-api.")
w("--")
w("-- Replaces 37 MySQL migrations with one schema rather than porting the history.")
w("-- Two reasons that is not laziness: several of them do not translate one for")
w("-- one, and the chain cannot build a database from scratch anyway -- the trigger")
w("-- migrations (000026-000028) are bare CREATE TRIGGER ... BEGIN ... END with no")
w("-- DELIMITER, so any client that splits on ';' dies partway through.")
w("--")
w("-- Generated from the schema those migrations actually produce, captured out of")
w("-- information_schema after applying them to a throwaway MySQL. Translating the")
w("-- migration text by hand would have carried their bugs across; see the")
w("-- idx_relations_* note below for one it caught.")
w("")
w("-- Index changes made deliberately during conversion:")
for n in notes:
    w(n)
w("")
w("CREATE EXTENSION IF NOT EXISTS unaccent;")
w("")
w("-- unaccent() is STABLE, not IMMUTABLE: the one-argument form looks up the")
w("-- default dictionary in the catalog, so Postgres refuses it in a generated")
w("-- column. Naming the dictionary explicitly removes that lookup, which is what")
w("-- makes this wrapper honest enough to mark IMMUTABLE -- the same pattern the")
w("-- Postgres docs use for unaccent-based indexes.")
w("--")
w("-- The caveat is real: if the unaccent dictionary is ever redefined, stored")
w("-- values here will not recompute. That is a deployment-time concern, not a")
w("-- runtime one, and the alternative is not having the column at all.")
w("CREATE OR REPLACE FUNCTION immutable_unaccent(text) RETURNS text")
w("  LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS")
w("$$ SELECT unaccent('unaccent', $1) $$;")
w("")

for tbl, cs in cols.items():
    w(f"-- {'-' * 70}")
    w(f"CREATE TABLE {tbl} (")
    parts = []
    checks = []
    for c in cs:
        if tbl == "anime_staff" and c["name"] == "url_slug":
            parts.append(
                f"  {c['name']} varchar(255) GENERATED ALWAYS AS ({URL_SLUG_EXPR}) STORED"
            )
            continue
        seg = f"  {c['name']} {pgtype(c)}"
        if c["type"].startswith("enum("):
            vals = ", ".join(f"'{v}'" for v in enum_values(c["type"]))
            checks.append(f"  CONSTRAINT {tbl}_{c['name']}_check CHECK ({c['name']} IN ({vals}))")
        if c["nullable"] == "NO" and c["extra"] != "auto_increment":
            seg += " NOT NULL"
        d = c["default"]
        if d != "~" and c["extra"] != "auto_increment":
            if d.upper() in ("CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP(3)"):
                seg += " DEFAULT now()"
            elif re.match(r"^-?[\d.]+$", d):
                seg += f" DEFAULT {d}"
            else:
                seg += f" DEFAULT '{d}'"
        parts.append(seg)
    if tbl in pk:
        parts.append(f"  PRIMARY KEY ({', '.join(pk[tbl])})")
    parts.extend(checks)
    w(",\n".join(parts))
    w(");")
    w("")
    for i in idx.get(tbl, []):
        u = "UNIQUE " if i["unique"] else ""
        w(f"CREATE {u}INDEX {i['name']} ON {tbl} ({', '.join(i['cols'])});")
    w("")

# ------------------------------------------------------ ON UPDATE CURRENT_TIMESTAMP
on_update = sorted({
    t for t, cs in cols.items()
    for c in cs if "on update" in c["extra"]
})
w("-- " + "-" * 70)
w("-- MySQL's ON UPDATE CURRENT_TIMESTAMP has no Postgres equivalent, so the")
w("-- columns that relied on it need a trigger to keep behaving the same way.")
w("-- Without this they would silently stop advancing on UPDATE -- a difference")
w("-- that does not fail anything, it just quietly makes updated_at wrong.")
w("CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$")
w("BEGIN")
w("  NEW.updated_at = now();")
w("  RETURN NEW;")
w("END;")
w("$$ LANGUAGE plpgsql;")
w("")
for t in on_update:
    w(f"CREATE TRIGGER {t}_set_updated_at BEFORE UPDATE ON {t}")
    w(f"  FOR EACH ROW EXECUTE FUNCTION set_updated_at();")
w("")

# ------------------------------------------------------------- episode triggers
w("-- " + "-" * 70)
w("-- anime.episodes is a denormalised count maintained by triggers on episodes.")
w("-- One plpgsql function covers all three events; the MySQL original was three")
w("-- near-identical trigger bodies.")
w("CREATE OR REPLACE FUNCTION update_anime_episode_count() RETURNS trigger AS $$")
w("DECLARE")
w("  target text;")
w("BEGIN")
w("  target := COALESCE(NEW.anime_id, OLD.anime_id);")
w("  UPDATE anime SET episodes = (")
w("    SELECT COUNT(*) FROM episodes WHERE anime_id = target")
w("  ) WHERE id = target;")
w("  RETURN NULL;")
w("END;")
w("$$ LANGUAGE plpgsql;")
w("")
for ev in ("INSERT", "UPDATE", "DELETE"):
    w(f"CREATE TRIGGER update_anime_episode_count_after_{ev.lower()}")
    w(f"  AFTER {ev} ON episodes")
    w(f"  FOR EACH ROW EXECUTE FUNCTION update_anime_episode_count();")
w("")

# ------------------------------------------------------------- the caught bug
w("-- " + "-" * 70)
w("-- 000021 tried to index a table named 'relations'. The table is")
w("-- anime_relations (000009), so these two indexes were never created -- not")
w("-- here and not in production, where that migration must have failed at the")
w("-- same line. Created correctly here rather than faithfully reproducing the")
w("-- typo.")
w("CREATE INDEX idx_relations_anime_id ON anime_relations (anime_id);")
w("CREATE INDEX idx_relations_related_anime_id ON anime_relations (related_anime_id);")

open(f"{OUT}/000001_baseline.up.sql", "w").write("\n".join(lines) + "\n")
print(f"wrote {len(lines)} lines, {len(cols)} tables, "
      f"{sum(len(v) for v in idx.values())} indexes, "
      f"{len(on_update)} updated_at triggers")
