package anime_staff

import (
	"context"
	"time"

	"github.com/weeb-vip/anime-api/internal/db"
	"github.com/weeb-vip/anime-api/metrics"
)

type AnimeStaffRepositoryImpl interface {
	FindStaffByID(ctx context.Context, id string) (*AnimeStaff, error)
	FindStaffBySlug(ctx context.Context, slug string) (*AnimeStaff, error)
}

type AnimeStaffRepository struct {
	db *db.DB
}

func NewAnimeStaffRepository(db *db.DB) AnimeStaffRepositoryImpl {
	return &AnimeStaffRepository{db: db}
}

func (a *AnimeStaffRepository) FindStaffByID(ctx context.Context, id string) (*AnimeStaff, error) {
	startTime := time.Now()

	var staff AnimeStaff
	err := a.db.DB.WithContext(ctx).Where("id = ?", id).First(&staff).Error
	if err != nil {
		metrics.GetAppMetrics().DatabaseSince(startTime, "anime_staff", metrics.MethodSelect, metrics.Error)
		return nil, err
	}

	metrics.GetAppMetrics().DatabaseSince(startTime, "anime_staff", metrics.MethodSelect, metrics.Success)
	return &staff, nil
}

// FindStaffBySlug looks a staff member up by their public URL segment.
//
// The slug is not normalised here. It is generated by the database from the
// name and only ever reaches us from a link this API produced, so an input that
// does not match a row is a bad URL rather than a spelling to be corrected --
// the same contract animeBySlug has.
//
// Four slugs in the table are held by two rows each, always the same person
// recorded twice under spelling variants (Daniel García / Daniel Garcia). First
// wins. Both rows describe the same person, so either answer is right; what
// differs is which subset of their credits is shown, and deduplicating the
// underlying rows is the actual fix.
func (a *AnimeStaffRepository) FindStaffBySlug(ctx context.Context, slug string) (*AnimeStaff, error) {
	startTime := time.Now()

	var staff AnimeStaff
	err := a.db.DB.WithContext(ctx).Where("url_slug = ?", slug).First(&staff).Error
	if err != nil {
		metrics.GetAppMetrics().DatabaseSince(startTime, "anime_staff", metrics.MethodSelect, metrics.Error)
		return nil, err
	}

	metrics.GetAppMetrics().DatabaseSince(startTime, "anime_staff", metrics.MethodSelect, metrics.Success)
	return &staff, nil
}
